openapi: 3.2.0
info:
  title: Google Drive Labels Limits API
  description: An API for managing Drive Labels
  version: v2
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
servers:
- url: https://drivelabels.googleapis.com
  description: Google Drive Labels API Server
tags:
- name: Limits
  description: Operations related to Limits
paths:
  /v2/limits/label:
    get:
      tags:
      - Limits
      summary: Google Retrieve Limits Label
      description: Get the constraints on the structure of a Label; such as, the maximum number of Fields allowed and maximum length of the label title.
      operationId: googleDrivelabelsLimitsGetlabel
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels.readonly
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive.admin.labels: See, edit, create, and delete all Google Drive labels in your organization, and see your organization's label-related admin policies
            https://www.googleapis.com/auth/drive.admin.labels.readonly: See all Google Drive labels and label-related admin policies in your organization
            https://www.googleapis.com/auth/drive.labels: See, edit, create, and delete your Google Drive labels
            https://www.googleapis.com/auth/drive.labels.readonly: See your Google Drive labels
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive.admin.labels: See, edit, create, and delete all Google Drive labels in your organization, and see your organization's label-related admin policies
            https://www.googleapis.com/auth/drive.admin.labels.readonly: See all Google Drive labels and label-related admin policies in your organization
            https://www.googleapis.com/auth/drive.labels: See, edit, create, and delete your Google Drive labels
            https://www.googleapis.com/auth/drive.labels.readonly: See your Google Drive labels
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2