openapi: 3.2.0
info:
  title: Google Gmail Patch API
  description: The Gmail API is a RESTful API that can be used to access Gmail mailboxes and send mail. For most web applications the Gmail API is the best choice for authorized access to a user's Gmail data and is suitable for various applications.
  version: 1.0.0
servers:
- url: https://gmail.googleapis.com
  description: Google Gmail API Server
security:
- oauth2Auth: []
tags:
- name: Patch
  description: Operations related to Patch
paths:
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}:
    patch:
      tags:
      - Patch
      summary: Google Patch Send As
      description: Patch the specified send-as alias.
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      - name: sendAsEmail
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersSettingsSendAsPatchRequest'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersSettingsSendAsPatchResponse'
              examples:
                UsersSettingsSendAsPatchResponseExample:
                  $ref: '#/components/examples/UsersSettingsSendAsPatchResponseExample'
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: UsersSettingsSendAsPatchResponseExample
  /gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}:
    patch:
      tags:
      - Patch
      summary: Google PATCH CSE Identites
      description: Associates a different key pair with an existing client-side encryption identity. The updated key pair must validate against Google's [S/MIME certificate profiles](https://support.google.com/a/answer/7300887).
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      - name: emailAddress
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingsCseIdentitiesPatchRequest'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsCseIdentitiesPatchResponse'
              examples:
                SettingsCseIdentitiesPatchResponseExample:
                  $ref: '#/components/examples/SettingsCseIdentitiesPatchResponseExample'
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SettingsCseIdentitiesPatchResponseExample
components:
  examples:
    UsersSettingsSendAsPatchResponseExample:
      summary: Successful 200 response
      value:
        sendAsEmail: ut nulla
        displayName: Excepteur
        replyToAddress: velit id culpa
        signature: officia quis adipisicing
        isPrimary: true
        isDefault: true
        treatAsAlias: false
        smtpMsa:
          host: in elit
          port: -34532702
          username: aliqua laborum aliquip do
          password: tempor dolor velit
          securityMode: securityModeUnspecified
        verificationStatus: pending
    SettingsCseIdentitiesPatchResponseExample:
      summary: Successful 200 response
      value:
        emailAddress: aliquip quis id
        primaryKeyPairId: in exercitation esse
        signAndEncryptKeyPairs:
          signingKeyPairId: est deserunt
          encryptionKeyPairId: elit nulla esse ut
  schemas:
    UsersSettingsSendAsPatchResponseSmtpMsa:
      description: UsersSettingsSendAsPatchResponseSmtpMsa schema
      type: object
      properties:
        host:
          type: string
        port:
          type: integer
        username:
          type: string
        password:
          type: string
        securityMode:
          type: string
    SettingsCseIdentitiesPatchRequest:
      description: SettingsCseIdentitiesPatchRequest schema
      type: object
      example:
        emailAddress: aliquip quis id
        primaryKeyPairId: in exercitation esse
        signAndEncryptKeyPairs:
          signingKeyPairId: est deserunt
          encryptionKeyPairId: elit nulla esse ut
    SettingsCseIdentitiesPatchResponse:
      description: SettingsCseIdentitiesPatchResponse schema
      type: object
      properties:
        emailAddress:
          type: string
        primaryKeyPairId:
          type: string
        signAndEncryptKeyPairs:
          $ref: '#/components/schemas/SettingsCseIdentitiesPatchResponseSignAndEncryptKeyPairs'
    UsersSettingsSendAsPatchResponse:
      description: UsersSettingsSendAsPatchResponse schema
      type: object
      properties:
        sendAsEmail:
          type: string
        displayName:
          type: string
        replyToAddress:
          type: string
        signature:
          type: string
        isPrimary:
          type: boolean
        isDefault:
          type: boolean
        treatAsAlias:
          type: boolean
        smtpMsa:
          $ref: '#/components/schemas/UsersSettingsSendAsPatchResponseSmtpMsa'
        verificationStatus:
          type: string
    UsersSettingsSendAsPatchRequest:
      description: UsersSettingsSendAsPatchRequest schema
      type: object
      example:
        sendAsEmail: ut nulla
        displayName: Excepteur
        replyToAddress: velit id culpa
        signature: officia quis adipisicing
        isPrimary: true
        isDefault: true
        treatAsAlias: false
        smtpMsa:
          host: in elit
          port: -34532702
          username: aliqua laborum aliquip do
          password: tempor dolor velit
          securityMode: securityModeUnspecified
        verificationStatus: pending
    SettingsCseIdentitiesPatchResponseSignAndEncryptKeyPairs:
      description: SettingsCseIdentitiesPatchResponseSignAndEncryptKeyPairs schema
      type: object
      properties:
        signingKeyPairId:
          type: string
        encryptionKeyPairId:
          type: string
  securitySchemes:
    oauth2Auth:
      type: http
      scheme: oauth2
