openapi: 3.1.0
info:
  title: Google Books About Files API
  description: API for retrieving Bookshelf and Volume resources from Google Books
  version: 1.0.0
  contact:
    name: Google Books API
    url: https://developers.google.com/books
servers:
- url: https://www.googleapis.com/books/v1
  description: Google Books API v1
tags:
- name: Files
  description: Operations related to Files
paths:
  /files:
    get:
      tags:
      - Files
      summary: Google Get Files
      description: ' Lists the user''s files. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for files & folders](/drive/api/guides/search-files) guide. *Note:* This method returns *all* files by default, including trashed files. If you don''t want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.'
      operationId: googleDriveFilesList
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      x-api-evangelist-certified: '2025-07-18'
      x-api-naftiko-published: '2025-07-18'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
    post:
      tags:
      - Files
      summary: Google Post Files
      description: ' Creates a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/drive/api/guides/manage-uploads). Apps creating shortcuts with `files.[...]'
      operationId: googleDriveFilesCreate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
  /files/generateIds:
    get:
      tags:
      - Files
      summary: Google Get Files Generateids
      description: Generates a set of file IDs which can be provided in create or copy requests.
      operationId: googleDriveFilesGenerateids
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
  /files/trash:
    delete:
      tags:
      - Files
      summary: Google Delete Files Trash
      description: Permanently deletes all of the user's trashed files.
      operationId: googleDriveFilesEmptytrash
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
  /files/{fileId}:
    get:
      tags:
      - Files
      summary: Google Get Files Fileid
      description: ' Gets a file''s metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/drive/api/reference/rest/v3/files/export) instead. For more information, see [Download & export files](/drive/api/guides/manage-downloads).'
      operationId: googleDriveFilesGet
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      x-api-evangelist-certified: '2025-07-18'
      x-api-naftiko-published: '2025-07-18'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
    patch:
      tags:
      - Files
      summary: Google Patch Files Fileid
      description: ' Updates a file''s metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the lit[...]'
      operationId: googleDriveFilesUpdate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.scripts
        Oauth2c:
        - https://www.googleapis.com/auth/drive.scripts
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
    delete:
      tags:
      - Files
      summary: Google Delete Files Fileid
      description: Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted.
      operationId: googleDriveFilesDelete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
  /files/{fileId}/copy:
    post:
      tags:
      - Files
      summary: Google Post Files Fileid Copy
      description: Creates a copy of a file and applies any requested updates with patch semantics.
      operationId: googleDriveFilesCopy
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
  /files/{fileId}/export:
    get:
      tags:
      - Files
      summary: Google Get Files Fileid Export
      description: Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.
      operationId: googleDriveFilesExport
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
  /files/{fileId}/listLabels:
    get:
      tags:
      - Files
      summary: Google Get Files Fileid Listlabels
      description: Lists the labels on a file.
      operationId: googleDriveFilesListlabels
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      x-api-evangelist-certified: '2025-07-18'
      x-api-naftiko-published: '2025-07-18'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
  /files/{fileId}/modifyLabels:
    post:
      tags:
      - Files
      summary: Google Post Files Fileid Modifylabels
      description: Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.
      operationId: googleDriveFilesModifylabels
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
  /files/{fileId}/watch:
    post:
      tags:
      - Files
      summary: Google Post Files Fileid Watch
      description: Subscribes to changes to a file.
      operationId: googleDriveFilesWatch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: OAuth 2.0 authentication for Google Books API
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            https://www.googleapis.com/auth/books: Manage your Google Books library
