openapi: 3.2.0
info:
  title: Google Gmail Disables API
  description: The Gmail API is a RESTful API that can be used to access Gmail mailboxes and send mail. For most web applications the Gmail API is the best choice for authorized access to a user's Gmail data and is suitable for various applications.
  version: 1.0.0
servers:
- url: https://gmail.googleapis.com
  description: Google Gmail API Server
security:
- oauth2Auth: []
tags:
- name: Disables
  description: Operations related to Disables
paths:
  /gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable:
    post:
      tags:
      - Disables
      summary: Google Disable CSE Keypairs
      description: Turns off a client-side encryption key pair. The authenticated user can no longer use the key pair to decrypt incoming CSE message texts or sign outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on the key pair. After 30 days, you can permanently delete the key pair by using the ObliterateCseKeyPair method.
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      - name: keyPairId
        in: path
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingsCseKeypairsPostRequest1'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsCseKeypairsPostResponse1'
              examples:
                SettingsCseKeypairsPostResponse1Example:
                  $ref: '#/components/examples/SettingsCseKeypairsPostResponse1Example'
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SettingsCseKeypairsPostResponse1Example
components:
  schemas:
    SettingsCseKeypairsPostResponse1:
      description: SettingsCseKeypairsPostResponse1 schema
      type: object
      properties:
        keyPairId:
          type: string
        pkcs7:
          type: string
        pem:
          type: string
        subjectEmailAddresses:
          type: array
          items:
            type: string
        enablementState:
          type: string
        disableTime:
          type: string
        privateKeyMetadata:
          type: array
          items:
            type: object
            properties:
              privateKeyMetadataId:
                type: string
              kaclsKeyMetadata:
                type: object
                properties:
                  kaclsUri:
                    type: string
                  kaclsData:
                    type: string
              hardwareKeyMetadata:
                type: object
                properties:
                  description:
                    type: string
    SettingsCseKeypairsPostRequest1:
      description: SettingsCseKeypairsPostRequest1 schema
      type: object
      example: {}
  examples:
    SettingsCseKeypairsPostResponse1Example:
      summary: Successful 200 response
      value:
        keyPairId: Lorem eiusmod
        pkcs7: ex incididunt
        pem: irure quis
        subjectEmailAddresses:
        - Excepteur Ut commodo aliquip
        - eu Lorem nulla
        enablementState: disabled
        disableTime: cill
        privateKeyMetadata:
        - privateKeyMetadataId: proident fugiat eu dolore
          kaclsKeyMetadata:
            kaclsUri: voluptate ipsum ad
            kaclsData: Duis laborum aute
          hardwareKeyMetadata:
            description: mollit la
        - privateKeyMetadataId: nulla ullamco
          kaclsKeyMetadata:
            kaclsUri: minim in
            kaclsData: sint eiusmod
          hardwareKeyMetadata:
            description: ut
  securitySchemes:
    oauth2Auth:
      type: http
      scheme: oauth2
