openapi: 3.2.0
info:
  title: Google Gmail Send API
  description: The Gmail API is a RESTful API that can be used to access Gmail mailboxes and send mail. For most web applications the Gmail API is the best choice for authorized access to a user's Gmail data and is suitable for various applications.
  version: 1.0.0
servers:
- url: https://gmail.googleapis.com
  description: Google Gmail API Server
security:
- oauth2Auth: []
tags:
- name: Send
  description: Operations related to Send
paths:
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify:
    post:
      tags:
      - Send
      summary: Google Verify Send As
      description: Sends a verification email to the specified send-as alias address. The verification status must be `pending`. This method is only available to service account clients that have been delegated domain-wide authority.
      parameters:
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      - name: sendAsEmail
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      requestBody:
        content: {}
      responses:
        '204':
          description: No Content
          content:
            text/plain:
              schema:
                type: string
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}:
    put:
      tags:
      - Send
      summary: Google Update Send As Setting
      description: Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      - name: sendAsEmail
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersSettingsSendAsPutRequest'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersSettingsSendAsPutResponse'
              examples:
                UsersSettingsSendAsPutResponseExample:
                  $ref: '#/components/examples/UsersSettingsSendAsPutResponseExample'
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: UsersSettingsSendAsPutResponseExample
components:
  schemas:
    UsersSettingsSendAsPutResponse:
      description: UsersSettingsSendAsPutResponse schema
      type: object
      properties:
        sendAsEmail:
          type: string
        displayName:
          type: string
        replyToAddress:
          type: string
        signature:
          type: string
        isPrimary:
          type: boolean
        isDefault:
          type: boolean
        treatAsAlias:
          type: boolean
        smtpMsa:
          $ref: '#/components/schemas/UsersSettingsSendAsPutResponseSmtpMsa'
        verificationStatus:
          type: string
    UsersSettingsSendAsPutResponseSmtpMsa:
      description: UsersSettingsSendAsPutResponseSmtpMsa schema
      type: object
      properties:
        host:
          type: string
        port:
          type: integer
        username:
          type: string
        password:
          type: string
        securityMode:
          type: string
    UsersSettingsSendAsPutRequest:
      description: UsersSettingsSendAsPutRequest schema
      type: object
      example:
        sendAsEmail: ut nulla
        displayName: Excepteur
        replyToAddress: velit id culpa
        signature: officia quis adipisicing
        isPrimary: true
        isDefault: true
        treatAsAlias: false
        smtpMsa:
          host: in elit
          port: -34532702
          username: aliqua laborum aliquip do
          password: tempor dolor velit
          securityMode: securityModeUnspecified
        verificationStatus: pending
  examples:
    UsersSettingsSendAsPutResponseExample:
      summary: Successful 200 response
      value:
        sendAsEmail: ut nulla
        displayName: Excepteur
        replyToAddress: velit id culpa
        signature: officia quis adipisicing
        isPrimary: true
        isDefault: true
        treatAsAlias: false
        smtpMsa:
          host: in elit
          port: -34532702
          username: aliqua laborum aliquip do
          password: tempor dolor velit
          securityMode: securityModeUnspecified
        verificationStatus: pending
  securitySchemes:
    oauth2Auth:
      type: http
      scheme: oauth2
